@api = http://localhost:3020/api/v1/usuarios
### GET
GET {{api}}
### GET ITEM
GET {{api}}/Brian
### GET ITEM
GET {{api}}/Jaimito?keyType=BK

###PUT Usuarios ITEM
POST {{api}}
Content-Type: application/json

{

  "IdUsuarioOK": "18401145",
  "IdUsuarioBK": "llanos",
  "Nombres": "Hector Izcoatl",
  "Apellidos": "Llanos Godoy",
  "Hotel": "Las Palomas",
  "Rol": "1",
  "Clave": "123",
  "CorreoEle": "heizllanosgo@ittepic.com.mx",
  "Celular": "3112356094",
  "Generated": false,
  "Activo": true


}

###PUT Usuarios ITEM
PUT {{api}}/Jaimito
Content-Type: application/json

{
    "IdUsuarioBK": "Jared",
    "Nombres": "Jared de Jesus",
    "Apellidos": "Zavala Leal", 
    "Clave": "184011",
    "CorreoEle": "jjared@ittepic.com.mx", 
    "Celular": "3112156489"

}
